// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: in_game_msg.proto

#include "in_game_msg.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace msg {
constexpr InGameInfo::InGameInfo(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : in_game_type_(0)
  , id_(0)
  , row_(0)
  , beredside_(false)
  , redwin_(false)
  , col_(0){}
struct InGameInfoDefaultTypeInternal {
  constexpr InGameInfoDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~InGameInfoDefaultTypeInternal() {}
  union {
    InGameInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT InGameInfoDefaultTypeInternal _InGameInfo_default_instance_;
}  // namespace msg
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_in_5fgame_5fmsg_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_in_5fgame_5fmsg_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_in_5fgame_5fmsg_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_in_5fgame_5fmsg_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::msg::InGameInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::msg::InGameInfo, in_game_type_),
  PROTOBUF_FIELD_OFFSET(::msg::InGameInfo, beredside_),
  PROTOBUF_FIELD_OFFSET(::msg::InGameInfo, id_),
  PROTOBUF_FIELD_OFFSET(::msg::InGameInfo, row_),
  PROTOBUF_FIELD_OFFSET(::msg::InGameInfo, col_),
  PROTOBUF_FIELD_OFFSET(::msg::InGameInfo, redwin_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::msg::InGameInfo)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::msg::_InGameInfo_default_instance_),
};

const char descriptor_table_protodef_in_5fgame_5fmsg_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021in_game_msg.proto\022\003msg\"k\n\nInGameInfo\022\024"
  "\n\014in_game_type\030\001 \001(\005\022\021\n\tbeRedSide\030\002 \001(\010\022"
  "\n\n\002id\030\003 \001(\005\022\013\n\003row\030\004 \001(\005\022\013\n\003col\030\005 \001(\005\022\016\n"
  "\006redWin\030\006 \001(\010B\225\001\n\033com.example.tutorial.p"
  "rotosB\021AddressBookProtosP\001Z:github.com/p"
  "rotocolbuffers/protobuf/examples/go/tuto"
  "rialpb\252\002$Google.Protobuf.Examples.Addres"
  "sBookb\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_in_5fgame_5fmsg_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_in_5fgame_5fmsg_2eproto = {
  false, false, 293, descriptor_table_protodef_in_5fgame_5fmsg_2eproto, "in_game_msg.proto", 
  &descriptor_table_in_5fgame_5fmsg_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_in_5fgame_5fmsg_2eproto::offsets,
  file_level_metadata_in_5fgame_5fmsg_2eproto, file_level_enum_descriptors_in_5fgame_5fmsg_2eproto, file_level_service_descriptors_in_5fgame_5fmsg_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK ::PROTOBUF_NAMESPACE_ID::Metadata
descriptor_table_in_5fgame_5fmsg_2eproto_metadata_getter(int index) {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_in_5fgame_5fmsg_2eproto);
  return descriptor_table_in_5fgame_5fmsg_2eproto.file_level_metadata[index];
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_in_5fgame_5fmsg_2eproto(&descriptor_table_in_5fgame_5fmsg_2eproto);
namespace msg {

// ===================================================================

class InGameInfo::_Internal {
 public:
};

InGameInfo::InGameInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:msg.InGameInfo)
}
InGameInfo::InGameInfo(const InGameInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&in_game_type_, &from.in_game_type_,
    static_cast<size_t>(reinterpret_cast<char*>(&col_) -
    reinterpret_cast<char*>(&in_game_type_)) + sizeof(col_));
  // @@protoc_insertion_point(copy_constructor:msg.InGameInfo)
}

void InGameInfo::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&in_game_type_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&col_) -
    reinterpret_cast<char*>(&in_game_type_)) + sizeof(col_));
}

InGameInfo::~InGameInfo() {
  // @@protoc_insertion_point(destructor:msg.InGameInfo)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void InGameInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void InGameInfo::ArenaDtor(void* object) {
  InGameInfo* _this = reinterpret_cast< InGameInfo* >(object);
  (void)_this;
}
void InGameInfo::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void InGameInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void InGameInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:msg.InGameInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&in_game_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&col_) -
      reinterpret_cast<char*>(&in_game_type_)) + sizeof(col_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InGameInfo::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 in_game_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          in_game_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool beRedSide = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          beredside_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 row = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          row_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 col = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          col_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool redWin = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          redwin_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* InGameInfo::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:msg.InGameInfo)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 in_game_type = 1;
  if (this->in_game_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_in_game_type(), target);
  }

  // bool beRedSide = 2;
  if (this->beredside() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(2, this->_internal_beredside(), target);
  }

  // int32 id = 3;
  if (this->id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_id(), target);
  }

  // int32 row = 4;
  if (this->row() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(4, this->_internal_row(), target);
  }

  // int32 col = 5;
  if (this->col() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(5, this->_internal_col(), target);
  }

  // bool redWin = 6;
  if (this->redwin() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(6, this->_internal_redwin(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:msg.InGameInfo)
  return target;
}

size_t InGameInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:msg.InGameInfo)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 in_game_type = 1;
  if (this->in_game_type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_in_game_type());
  }

  // int32 id = 3;
  if (this->id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_id());
  }

  // int32 row = 4;
  if (this->row() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_row());
  }

  // bool beRedSide = 2;
  if (this->beredside() != 0) {
    total_size += 1 + 1;
  }

  // bool redWin = 6;
  if (this->redwin() != 0) {
    total_size += 1 + 1;
  }

  // int32 col = 5;
  if (this->col() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_col());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void InGameInfo::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:msg.InGameInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const InGameInfo* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<InGameInfo>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:msg.InGameInfo)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:msg.InGameInfo)
    MergeFrom(*source);
  }
}

void InGameInfo::MergeFrom(const InGameInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:msg.InGameInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.in_game_type() != 0) {
    _internal_set_in_game_type(from._internal_in_game_type());
  }
  if (from.id() != 0) {
    _internal_set_id(from._internal_id());
  }
  if (from.row() != 0) {
    _internal_set_row(from._internal_row());
  }
  if (from.beredside() != 0) {
    _internal_set_beredside(from._internal_beredside());
  }
  if (from.redwin() != 0) {
    _internal_set_redwin(from._internal_redwin());
  }
  if (from.col() != 0) {
    _internal_set_col(from._internal_col());
  }
}

void InGameInfo::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:msg.InGameInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void InGameInfo::CopyFrom(const InGameInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:msg.InGameInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InGameInfo::IsInitialized() const {
  return true;
}

void InGameInfo::InternalSwap(InGameInfo* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(InGameInfo, col_)
      + sizeof(InGameInfo::col_)
      - PROTOBUF_FIELD_OFFSET(InGameInfo, in_game_type_)>(
          reinterpret_cast<char*>(&in_game_type_),
          reinterpret_cast<char*>(&other->in_game_type_));
}

::PROTOBUF_NAMESPACE_ID::Metadata InGameInfo::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace msg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::msg::InGameInfo* Arena::CreateMaybeMessage< ::msg::InGameInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::msg::InGameInfo >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
